### ISSUE TITLE
[BUG] no coverart in Favourites - detail screen

### ISSUE THREAD

**Issue by ac3nl** [Sichroteph/Onion#4]
### Checklist

- [X] I am reporting a bug in the Onion OS
- [X] I have reviewed the Onion Wiki and did not find the answer ([Wiki](https://github.com/Sichroteph/Onion/wiki))
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

All versions

### Miyoo Firmware Version

0429

### Provide a clear and concise description of the issue

In my favourites list i do see images, however when i press dpad Right, no images are there.

in console list, i do see images, when i press dpad Right

### Steps to Reproduce

Goto favourites and press DPAD right
No art here, but it is in list view

### Provide any additional context or information that may help us investigate your issue

Is this onion related, i don”t know

**Comment by Olywa** [comment]
You just wanted to be the first to raise an issue on the new site didn't you ? 😉

Unfortunately this one is an issue in the Miyoo firmware/binaries (appreciate that's not obvious), it's not something the Onion team can easily fix without a significant amount of work and then the effort would out way the benefit. Hopefully Miyoo will fix it in a future FW release.
