### ISSUE TITLE
Wiki - Miyoo mini apps 

### ISSUE THREAD

**Issue by zebramonkeylizard** [Sichroteph/Onion#6]
### Checklist

- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and something is incorrect or missing

### Wiki Section

Miyoo mini apps > Sort favorites alphabetically

### Description

The file Sort.Fav.zip does not work as the sub folder under the App folder has spaces in it.

### Correction

"/Sort Favorites [Z-A]/App/**Sort Favorites [Z-A]**/" _should be_ "/Sort Favorites [Z-A]/App/**SortFavorites[Z-A]**/"
&
"/Sort Favorites [A-Z]/App/**Sort Favorites [A-Z]**/" _should be_ "/Sort Favorites [A-Z]/App/**SortFavorites[A-Z]**/"

### Provide any additional context or information that may help us with this update

Unzip the file, remove the spaces, and re-zip the file.

**Comment by Olywa** [comment]
@zebramonkeylizard I have just updated the zip so should be fixed now, please can you confirm.

**Comment by zebramonkeylizard** [comment]
Looks good.
